"""create qdrant

Revision ID: 4f4676fb6fb7
Revises: 9ad32bf56a90
Create Date: 2026-06-06 17:03:51.744409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4f4676fb6fb7'
down_revision: Union[str, Sequence[str], None] = '9ad32bf56a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('qdrant_point_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_knowledge_chunks_qdrant_point_id'), 'knowledge_chunks', ['qdrant_point_id'], unique=True)
    op.drop_column('knowledge_chunks', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('embedding', mysql.JSON(), nullable=False))
    op.drop_index(op.f('ix_knowledge_chunks_qdrant_point_id'), table_name='knowledge_chunks')
    op.drop_column('knowledge_chunks', 'qdrant_point_id')
    # ### end Alembic commands ###
