"""create long term memory tables

Revision ID: cea90686c96c
Revises: d890b714c8f1
Create Date: 2026-06-01 20:44:43.123808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea90686c96c'
down_revision: Union[str, Sequence[str], None] = 'd890b714c8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_session_id'), 'conversation_summaries', ['session_id'], unique=True)
    op.create_index(op.f('ix_conversation_summaries_user_id'), 'conversation_summaries', ['user_id'], unique=False)
    op.create_table('long_term_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('memory_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_term_memories_memory_id'), 'long_term_memories', ['memory_id'], unique=True)
    op.create_index(op.f('ix_long_term_memories_memory_type'), 'long_term_memories', ['memory_type'], unique=False)
    op.create_index(op.f('ix_long_term_memories_user_id'), 'long_term_memories', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('common_questions', sa.Text(), nullable=True),
    sa.Column('preference_summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('refund_count', sa.Integer(), nullable=False),
    sa.Column('complaint_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_long_term_memories_user_id'), table_name='long_term_memories')
    op.drop_index(op.f('ix_long_term_memories_memory_type'), table_name='long_term_memories')
    op.drop_index(op.f('ix_long_term_memories_memory_id'), table_name='long_term_memories')
    op.drop_table('long_term_memories')
    op.drop_index(op.f('ix_conversation_summaries_user_id'), table_name='conversation_summaries')
    op.drop_index(op.f('ix_conversation_summaries_session_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    # ### end Alembic commands ###
