"""create trace table

Revision ID: d890b714c8f1
Revises: c1f26be3c0ef
Create Date: 2026-06-01 17:43:50.207876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd890b714c8f1'
down_revision: Union[str, Sequence[str], None] = 'c1f26be3c0ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_traces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('agent_name', sa.String(length=64), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('step', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('tool_args', sa.Text(), nullable=True),
    sa.Column('tool_result', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_traces_agent_name'), 'agent_traces', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_traces_node_name'), 'agent_traces', ['node_name'], unique=False)
    op.create_index(op.f('ix_agent_traces_session_id'), 'agent_traces', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_trace_id'), 'agent_traces', ['trace_id'], unique=False)
    op.create_index(op.f('ix_agent_traces_user_id'), 'agent_traces', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_traces_user_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_trace_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_session_id'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_node_name'), table_name='agent_traces')
    op.drop_index(op.f('ix_agent_traces_agent_name'), table_name='agent_traces')
    op.drop_table('agent_traces')
    # ### end Alembic commands ###
